---
title: 'STAT 471/701: Project'
author: "Benson Chen, Kevin Lei"
output:
  pdf_document:
    toc: yes
  html_document:
    number_sections: yes
    self_contained: no
    toc: yes
  word_document: default
---
```{r setup_library, include=FALSE}
  knitr::opts_chunk$set(tidy=TRUE, fig.width=12,  fig.height=8)
  library(leaps)
  library(class)
  library(ISLR)
  library(MASS)  # load package MASS
  library(lattice) # xyplot(), bwplot()
  library(ggplot2)
  library(plotrix)
  library(pROC)
  library(glmnet)
  library(LiblineaR)
  library(tree)
  library(randomForest)
```

_________________________________________________________________________
# Introduction
**Background Information**


```{r setup_data, include=FALSE}
####### THE ACTUAL PDF WAS NO GENERATED WITH THIS KNITR FILE, WE DID IT THROUGH LATEX, BUT OUR R CODE IS HERE.
########

rm(list=ls()) # Remove all the existing variables

# dir=c("/Users/Benson/Desktop/stat471_final_proj")
dir=c("C:\\Users\\Kevin\\Documents\\University of Pennsylvania\\FALL 2015\\STAT 471\\Final Project\\code")
setwd(dir)

set.seed(37)

#includes data about champions
data_champs <- read.csv("data_champs.csv", header=T, stringsAsFactors=T, as.is=T, 
                   na.strings="")

#includes data about other statistics include response variable
data_stats <- read.csv("data_stats.csv", header=T, stringsAsFactors=T, as.is=T, 
                   na.strings="")

#things are split to make them easier to work with
```

# Data Overview

```{r champions, include=FALSE}

#take absolute value of all champions to count
pos = abs(data_champs)
pos_sums = colSums(pos)
names(pos_sums) = names(pos)

#plot histogram
hist(pos_sums, main="Histogram of Number of Champion Plays", xlab="Number of Champion Plays", ylab="Frequency", breaks=20, cex.lab=1.5, cex.axis=1.5, cex.main=1.5, cex.sub=1.5)

```


```{r minion_jungle=FALSE}
#aggregate data for minions/jungle camps
Top_MPM_0_10 = data_stats$TOP_zeroToTenCreeps_1 - data_stats$TOP_zeroToTenCreeps_2
Top_MPM_10_20 = data_stats$TOP_tenToTwentyCreeps_1 - data_stats$TOP_tenToTwentyCreeps_2

Mid_MPM_0_10 = data_stats$MIDDLE_zeroToTenCreeps_1 - data_stats$MIDDLE_zeroToTenCreeps_2
Mid_MPM_10_20 = data_stats$MIDDLE_tenToTwentyCreeps_1 - data_stats$MIDDLE_tenToTwentyCreeps_2

ADC_MPM_0_10 = data_stats$DUO_CARRY_zeroToTenCreeps_1 - data_stats$DUO_CARRY_zeroToTenCreeps_2
ADC_MPM_10_20 = data_stats$DUO_CARRY_tenToTwentyCreeps_1 - data_stats$DUO_CARRY_tenToTwentyCreeps_2


jungle_camps_diff = data_stats$neutral_jungle_1 - data_stats$neutral_jungle_2
minions_data = data.frame(Top_MPM_0_10, Top_MPM_10_20, Mid_MPM_0_10, Mid_MPM_10_20, ADC_MPM_0_10, ADC_MPM_10_20, jungle_camps_diff)
```


```{r wards=FALSE}
# Jungle ward variables
jg_total_wards_bought_1 = data_stats$sight_jungle_1+data_stats$vision_jungle_1
jg_total_wards_bought_2 = data_stats$sight_jungle_2+data_stats$vision_jungle_2

jg_total_wards_bought_diff = jg_total_wards_bought_1 - jg_total_wards_bought_2
jg_total_wards_placed_diff = data_stats$wards_placed_jungle_1 - data_stats$wards_placed_jungle_2
jg_total_wards_killed_diff = data_stats$wards_killed_jungle_1 - data_stats$wards_killed_jungle_2

# Support ward variables
supp_total_wards_bought_1 = data_stats$sight_support_1 + data_stats$vision_support_1
supp_total_wards_bought_2 = data_stats$sight_support_2 + data_stats$vision_support_2

supp_total_wards_bought_diff = supp_total_wards_bought_1 - supp_total_wards_bought_2
supp_total_wards_placed_diff = data_stats$wards_placed_support_1 - data_stats$wards_placed_support_2
supp_total_wards_killed_diff = data_stats$wards_killed_support_1 - data_stats$wards_killed_support_2

wards_data = data.frame(jg_total_wards_bought_diff, jg_total_wards_placed_diff, jg_total_wards_killed_diff, supp_total_wards_bought_diff, supp_total_wards_placed_diff, supp_total_wards_killed_diff)
named_wards_data = wards_data
names(named_wards_data) = c("Jungle Wards Bought Diff", "Jungle Wards Placed Diff", "Jungle Wards Killed Diff", "Support Wards Bought Diff", "Support Wards Placed Diff", "Support Wards Killed Diff")
pairs(named_wards_data)
```

```{r first_blood=FALSE}
#first blood variable
firstBlood = data_stats$firstBlood
first_blood_data = data.frame(firstBlood)
```

```{r dragon/baron=FALSE}
#dragon baron variables
dragon_1 = data_stats$dragon_1
dragon_2 = data_stats$dragon_2

baron_1 = data_stats$baron_1
baron_2 = data_stats$baron_2

dragon_baron_data = data.frame(dragon_1, dragon_2, baron_1, baron_2)
par(mfrow=c(1,2))
hist(dragon_1, main = "Histogram of Dragon Kills for Team 1", xlab ="Number of Dragon Kills", cex.lab=1.5, cex.axis=1.5, cex.main=1.5, cex.sub=1.5)
hist(dragon_2, main = "Histogram of Dragon Kills for Team 2", xlab ="Number of Dragon Kills", cex.lab=1.5, cex.axis=1.5, cex.main=1.5, cex.sub=1.5)

hist(baron_1, main = "Histogram of Baron Kills for Team 1", xlab ="Number of Baron Kills", cex.lab=1.5, cex.axis=1.5, cex.main=1.5, cex.sub=1.5)
hist(baron_2, main = "Histogram of Baron Kills for Team 2", xlab ="Number of Baron Kills", cex.lab=1.5, cex.axis=1.5, cex.main=1.5, cex.sub=1.5)
par(mfrow=c(1,1))
```

```{r aggregate=FALSE}
#combine all x variables
x_data = cbind(data_champs, minions_data, wards_data, first_blood_data, dragon_baron_data)
winner = data_stats$winner
y_data = data.frame(winner)
```

```{r lasso=FALSE}
#LASSO, same as we did in class
x_mat = model.matrix(championId_266~., data=x_data)
y_mat = model.matrix(~., data=y_data)[, 2]
fit.cv_default = cv.glmnet(x_mat, y_mat, family="binomial", alpha=1.0, nfolds=10, type.measure="class") 
plot(fit.cv_default, cex.lab=1.5, cex.axis=1.5, cex.main=1.5, cex.sub=1.5)

#pick some value of lambda
new_lambda = exp(-3.8)
fit.select = glmnet(x_mat, y_mat, family="binomial", alpha=1.0, lambda = new_lambda)
fit.beta = coef(fit.select)
```

```{r train_test =FALSE}
#divide into test and train
train_index = sample(3000, size = 2000)
x_train = x_data[train_index, ]
y_train = y_data[train_index, ]

x_test = x_data[-train_index, ]
y_test = y_data[-train_index, ]
```
 
```{r logistic regression=FALSE}
#create actual LR
lr_model = glm(y_train~Top_MPM_0_10+Top_MPM_10_20+Mid_MPM_10_20+ADC_MPM_0_10+ADC_MPM_10_20+jungle_camps_diff+supp_total_wards_placed_diff+firstBlood+dragon_1+dragon_2+baron_1+baron_2,family=binomial(logit), data=x_train)

lr_model_reduced = glm(y_train~Top_MPM_10_20+Mid_MPM_10_20+ADC_MPM_10_20+jungle_camps_diff+supp_total_wards_placed_diff+firstBlood+dragon_1+dragon_2+baron_1+baron_2,family=binomial(logit), data=x_train)

#likelihood ratio test:
1-pchisq(lr_model_reduced$deviance-lr_model$deviance, lr_model_reduced$df.residual-lr_model$df.residual)

#predictions
lr_model.predict = predict(lr_model_reduced, x_test, type="response")
lr_class_labels = (lr_model.predict > 0.5) + 0
lr_model.roc=roc(y_test, lr_model.predict, plot=T)
lr_model.roc$auc
```

```{r decision_tree=FALSE}
y_class <- as.factor(y_mat)
y_class_train <- as.factor(y_train)
y_class_test <- as.factor(y_test)
rf_model <- randomForest(y_class_train~Top_MPM_0_10+Top_MPM_10_20+Mid_MPM_10_20+ADC_MPM_0_10+ADC_MPM_10_20+jungle_camps_diff+supp_total_wards_placed_diff+firstBlood+dragon_1+dragon_2+baron_1+baron_2, data=x_train, mtry=10, ntree=500)

# Plot the Random Forest to see the optimal number of trees
plot(rf_model, main="MCE vs. Number of Trees")
legend("topright", colnames(rf_model$err.rate),col=1:4,cex=0.8,fill=1:4)

# Get the confusion matrix
print(rf_model)
#     0     1
# 0   923   133
# 1   129   815
MCE <- (129+133) / (923+133+129+815)

# ROC Curve
rf_predict <- predict(rf_model, x_test, type='prob')
roc(y_test, rf_predict[, 2], plot=T)
rf_model$err.rate
names(rf_model)

importance(rf_model)
```